# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [bitcoinvn], bitcoinvietnam]
patreon: # Replace with a single Patreon username bitcoinvn
open_collective: # Replace with a single Open Collective username bitcoinvn
ko_fi: # Replace with a single Ko-fi username bitcoinvn 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username bitcoinvn
issuehunt: # Replace with a single IssueHunt username bitcoinvn
otechie: # Replace with a single Otechie username bitcoinvn 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['bitcoinvn.io', 'vbtc.exchange', 'bitcoinvn.io/api/doc', 'btm.bitcoinvn.io']
